### ISSUE TITLE
textfsm.TextFSMError

### ISSUE THREAD

**Issue by feisa** [networktocode/ntc-ansible#251]
Receiving the following error 

task path: /home/feisa/ansible-network/roles/ntc-test/tasks/main.yml:2
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: textfsm.TextFSMError: State Error raised. Rule Line: 19. Input Line: Port          Name               Status    Vlan      Duplex  Speed   Type
fatal: [tc1-leafc003]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/feisa/.ansible/tmp/ansible-local-20362or2skynw/ansible-tmp-1570055870.6327746-268558085523865/AnsiballZ_ntc_show_command.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/home/feisa/.ansible/tmp/ansible-local-20362or2skynw/ansible-tmp-1570055870.6327746-268558085523865/AnsiballZ_ntc_show_command.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/feisa/.ansible/tmp/ansible-local-20362or2skynw/ansible-tmp-1570055870.6327746-268558085523865/AnsiballZ_ntc_show_command.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_ntc_show_command_payload_U635Rz/__main__.py\", line 523, in <module>\n  File \"/tmp/ansible_ntc_show_command_payload_U635Rz/__main__.py\", line 510, in main\n  File \"/tmp/ansible_ntc_show_command_payload_U635Rz/__main__.py\", line 320, in parse_raw_output\n  File \"/tmp/ansible_ntc_show_command_payload_U635Rz/__main__.py\", line 296, in get_structured_data\n  File \"/usr/lib/python2.7/site-packages/clitable.py\", line 277, in ParseCmd\n    self.table = self._ParseCmdItem(self.raw, template_file=template_files[0])\n  File \"/usr/lib/python2.7/site-packages/clitable.py\", line 310, in _ParseCmdItem\n    for record in fsm.ParseText(cmd_input):\n  File \"/usr/lib/python2.7/site-packages/textfsm.py\", line 885, in ParseText\n    self._CheckLine(line)\n  File \"/usr/lib/python2.7/site-packages/textfsm.py\", line 908, in _CheckLine\n    if self._Operations(rule, line):\n  File \"/usr/lib/python2.7/site-packages/textfsm.py\", line 989, in _Operations\n    % (rule.line_num, line))\ntextfsm.TextFSMError: State Error raised. Rule Line: 19. Input Line: Port          Name               Status    Vlan      Duplex  Speed   Type\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
...ignoring
META: ran handlers
META: ran handlers

when running 

- name: Gather Info
  ntc_show_command:
    connection: ssh
    platform: cisco_nxos
    template_dir: /usr/lib/python2.7/site-packages/modules/ntc-ansible/ntc-templates/templates/
    command: 'show interface status'
    host: "{{ inventory_hostname }}"
    username: admin
    password: "{{ admin_passord }}"
  register: neighbors

ansible 2.8.4
  config file = /home/feisa/ansible-network/ansible.cfg
  configured module search path = ['/usr/lib/python2.7/site-packages/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug  7 2019, 17:28:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

**Comment by FragmentedPacket** [comment]
@feisa Could you post the sanitized raw output of the command?

**Comment by feisa** [comment]
Its an asnible task. do you just want the full role?

**Comment by feisa** [comment]
Its an asnible task. do you just want the full role?

**Comment by FragmentedPacket** [comment]
You can just do a `show interface status` on the device this failed for. We're looking to obtain the raw output so we can detect what needs to change within the template to account for the new data.

**Comment by feisa** [comment]
[output.txt](https://github.com/networktocode/ntc-ansible/files/3687292/output.txt)
 output attached

**Comment by FragmentedPacket** [comment]
@feisa Can you try and pull the latest from the ntc-templates repo? I tested the output you provided and I don't get an error.

It appears to have been fixed [Fixed commit](https://github.com/networktocode/ntc-templates/commit/8f99579a046a78259e64c3892d116a1eb87de39d#diff-181e864d0b154c645c661f3499ef860c)

**Comment by feisa** [comment]
I m using the latest but still received the error, i have a work around for now using another template

**Comment by FragmentedPacket** [comment]
How are you using the templates? Are you cloning them down or part of ntc-ansible?
